src/Entity/Medicament.php
<?php

namespace App\Entity;

use App\Repository\MedicamentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MedicamentRepository::class)
 */
class Medicament
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $nom_medi;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $dose_medi;

    /**
     * @ORM\OneToMany(targetEntity=Prescription::class, mappedBy="medcicament")
     */
    private $prescription;

    public function __construct()
    {
        $this->prescription = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomMedi(): ?string
    {
        return $this->nom_medi;
    }

    public function setNomMedi(string $nom_medi): self
    {
        $this->nom_medi = $nom_medi;

        return $this;
    }

    public function getDoseMedi(): ?string
    {
        return $this->dose_medi;
    }

    public function setDoseMedi(string $dose_medi): self
    {
        $this->dose_medi = $dose_medi;

        return $this;
    }

    /**
     * @return Collection|Prescription[]
     */
    public function getPrescription(): Collection
    {
        return $this->prescription;
    }

    public function addPrescription(Prescription $prescription): self
    {
        if (!$this->prescription->contains($prescription)) {
            $this->prescription[] = $prescription;
            $prescription->setMedcicament($this);
        }

        return $this;
    }

    public function removePrescription(Prescription $prescription): self
    {
        if ($this->prescription->contains($prescription)) {
            $this->prescription->removeElement($prescription);
            // set the owning side to null (unless already changed)
            if ($prescription->getMedcicament() === $this) {
                $prescription->setMedcicament(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNomMedi() ;
    }
}

src/Form/MedicamentType.php
<?php

namespace App\Form;

use App\Entity\Medicament;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MedicamentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_medi')
            ->add('dose_medi')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Medicament::class,
        ]);
    }
}

src/Controller/MedicamentController.php
<?php

namespace App\Controller;

use App\Entity\Medicament;
use App\Form\MedicamentType;
use App\Repository\MedicamentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/medicament")
 */
class MedicamentController extends AbstractController
{
    /**
     * @Route("/", name="medicament_index", methods={"GET"})
     */
    public function index(MedicamentRepository $medicamentRepository): Response
    {
        return $this->render('medicament/index.html.twig', [
            'medicaments' => $medicamentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="medicament_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $medicament = new Medicament();
        $form = $this->createForm(MedicamentType::class, $medicament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($medicament);
            $entityManager->flush();

            return $this->redirectToRoute('medicament_index');
        }

        return $this->render('medicament/new.html.twig', [
            'medicament' => $medicament,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="medicament_show", methods={"GET"})
     */
    public function show(Medicament $medicament): Response
    {
        return $this->render('medicament/show.html.twig', [
            'medicament' => $medicament,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="medicament_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Medicament $medicament): Response
    {
        $form = $this->createForm(MedicamentType::class, $medicament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('medicament_index');
        }

        return $this->render('medicament/edit.html.twig', [
            'medicament' => $medicament,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="medicament_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Medicament $medicament): Response
    {
        if ($this->isCsrfTokenValid('delete'.$medicament->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($medicament);
            $entityManager->flush();
        }

        return $this->redirectToRoute('medicament_index');
    }
}

templates/medicament/_delete_form.html.twig
<form method="post" action="{{ path('medicament_delete', {'id': medicament.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ medicament.id) }}">
    <button class="btn">Delete</button>
</form>

templates/medicament/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/medicament/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Medicament{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Edit Medicament</h1>

    {{ include('medicament/_form.html.twig', {'button_label': 'Update'}) }}

<div class="login-icon ml-2">
    <a class="" href="{{ path('medicament_index') }}"> back to list </a>
</div>

    {{ include('medicament/_delete_form.html.twig') }}
{% endblock %}

templates/medicament/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Medicament index{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Medicament index</h1>


    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_medi</th>
                <th>Dose_medi</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for medicament in medicaments %}
            <tr>
                <td>{{ medicament.id }}</td>
                <td>{{ medicament.nomMedi }}</td>
                <td>{{ medicament.doseMedi }}</td>
                <td><div class="login-icon ml-2">
                    <a class="" href="{{ path('medicament_show', {'id': medicament.id}) }}"> show </a>
                    <a class="" href="{{ path('medicament_edit', {'id': medicament.id}) }}"> edit </a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="login-icon ml-2">
<a class="" href="{{ path('medicament_new') }}"> Create new </a>
</div>

<div class="login-icon ml-2">
<a class="" href="{{ path('admin') }}"> Page admin </a>
</div>

{% endblock %}

templates/medicament/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Medicament{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Create new Medicament</h1>

    {{ include('medicament/_form.html.twig') }}

<div class="login-icon ml-2">
    <a class="" href="{{ path('medicament_index') }}"> back to list </a>
</div>
{% endblock %}

templates/medicament/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Medicament{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Medicament</h1>


    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ medicament.id }}</td>
            </tr>
            <tr>
                <th>Nom_medi</th>
                <td>{{ medicament.nomMedi }}</td>
            </tr>
            <tr>
                <th>Dose_medi</th>
                <td>{{ medicament.doseMedi }}</td>
            </tr>
            <td>
                <div class="login-icon ml-2">
                    <a class="" href="{{ path('medicament_index') }}"> back to list </a>

                    <a class="" href="{{ path('medicament_edit', {'id': medicament.id}) }}"> edit </a>
                </div>
            </td>
        </tbody>
    </table>

    {{ include('medicament/_delete_form.html.twig') }}
{% endblock %}