src/Entity/Prescription.php
<?php

namespace App\Entity;

use App\Repository\PrescriptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PrescriptionRepository::class)
 */
class Prescription
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbr_fois;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $quand_medi;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $forme_medi;

    /**
     * @ORM\OneToMany(targetEntity=Ordonance::class, mappedBy="prescription")
     */
    private $ordonance;

    /**
     * @ORM\ManyToOne(targetEntity=Medicament::class, inversedBy="prescription")
     * @ORM\JoinColumn(nullable=false)
     */
    private $medcicament;

    public function __construct()
    {
        $this->ordonance = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbrFois(): ?int
    {
        return $this->nbr_fois;
    }

    public function setNbrFois(int $nbr_fois): self
    {
        $this->nbr_fois = $nbr_fois;

        return $this;
    }

    public function getQuandMedi(): ?string
    {
        return $this->quand_medi;
    }

    public function setQuandMedi(string $quand_medi): self
    {
        $this->quand_medi = $quand_medi;

        return $this;
    }

    public function getFormeMedi(): ?string
    {
        return $this->forme_medi;
    }

    public function setFormeMedi(string $forme_medi): self
    {
        $this->forme_medi = $forme_medi;

        return $this;
    }

    /**
     * @return Collection|Ordonance[]
     */
    public function getOrdonance(): Collection
    {
        return $this->ordonance;
    }

    public function addOrdonance(Ordonance $ordonance): self
    {
        if (!$this->ordonance->contains($ordonance)) {
            $this->ordonance[] = $ordonance;
            $ordonance->setPrescription($this);
        }

        return $this;
    }

    public function removeOrdonance(Ordonance $ordonance): self
    {
        if ($this->ordonance->contains($ordonance)) {
            $this->ordonance->removeElement($ordonance);
            // set the owning side to null (unless already changed)
            if ($ordonance->getPrescription() === $this) {
                $ordonance->setPrescription(null);
            }
        }

        return $this;
    }

    public function getMedcicament(): ?Medicament
    {
        return $this->medcicament;
    }

    public function setMedcicament(?Medicament $medcicament): self
    {
        $this->medcicament = $medcicament;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getId() ;
    }
}

src/Form/PrescriptionType.php
<?php

namespace App\Form;

use App\Entity\Prescription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PrescriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nbr_fois')
            ->add('quand_medi')
            ->add('forme_medi')
            ->add('medcicament')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Prescription::class,
        ]);
    }
}

src/Controller/PrescriptionController.php
<?php

namespace App\Controller;

use App\Entity\Prescription;
use App\Form\PrescriptionType;
use App\Repository\PrescriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/prescription")
 */
class PrescriptionController extends AbstractController
{
    /**
     * @Route("/", name="prescription_index", methods={"GET"})
     */
    public function index(PrescriptionRepository $prescriptionRepository): Response
    {
        return $this->render('prescription/index.html.twig', [
            'prescriptions' => $prescriptionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="prescription_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $prescription = new Prescription();
        $form = $this->createForm(PrescriptionType::class, $prescription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($prescription);
            $entityManager->flush();

            return $this->redirectToRoute('prescription_index');
        }

        return $this->render('prescription/new.html.twig', [
            'prescription' => $prescription,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="prescription_show", methods={"GET"})
     */
    public function show(Prescription $prescription): Response
    {
        return $this->render('prescription/show.html.twig', [
            'prescription' => $prescription,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="prescription_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Prescription $prescription): Response
    {
        $form = $this->createForm(PrescriptionType::class, $prescription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('prescription_index');
        }

        return $this->render('prescription/edit.html.twig', [
            'prescription' => $prescription,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="prescription_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Prescription $prescription): Response
    {
        if ($this->isCsrfTokenValid('delete'.$prescription->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($prescription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('prescription_index');
    }
}

templates/prescription/_delete_form.html.twig
<form method="post" action="{{ path('prescription_delete', {'id': prescription.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ prescription.id) }}">
    <button class="btn">Delete</button>
</form>

templates/prescription/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/prescription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Prescription{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Edit Prescription</h1>

    {{ include('prescription/_form.html.twig', {'button_label': 'Update'}) }}

<div class="login-icon ml-2">
    <a class="" href="{{ path('prescription_index') }}"> back to list </a>
</div>

    {{ include('prescription/_delete_form.html.twig') }}
{% endblock %}

templates/prescription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prescription index{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Prescription index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nbr_fois</th>
                <th>Quand_medi</th>
                <th>Forme_medi</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for prescription in prescriptions %}
            <tr>
                <td>{{ prescription.id }}</td>
                <td>{{ prescription.nbrFois }}</td>
                <td>{{ prescription.quandMedi }}</td>
                <td>{{ prescription.formeMedi }}</td>
                <td><div class="login-icon ml-2">
                    <a class="" href="{{ path('prescription_show', {'id': prescription.id}) }}"> show </a>
                    <a class="" href="{{ path('prescription_edit', {'id': prescription.id}) }}"> edit </a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="login-icon ml-2">
<a class="" href="{{ path('prescription_new') }}"> Create new </a>
</div>

<div class="login-icon ml-2">
<a class="" href="{{ path('admin') }}"> Page admin </a>
</div>
{% endblock %}

templates/prescription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Prescription{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Create new Prescription</h1>

    {{ include('prescription/_form.html.twig') }}
<div class="login-icon ml-2">
    <a class="" href="{{ path('prescription_index') }}"> back to list </a>
</div>
{% endblock %}

templates/prescription/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prescription{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Prescription</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ prescription.id }}</td>
            </tr>
            <tr>
                <th>Nbr_fois</th>
                <td>{{ prescription.nbrFois }}</td>
            </tr>
            <tr>
                <th>Quand_medi</th>
                <td>{{ prescription.quandMedi }}</td>
            </tr>
            <tr>
                <th>Forme_medi</th>
                <td>{{ prescription.formeMedi }}</td>
            </tr>
            <tr>
                <th>Medicament</th>
                <td>{{ prescription.medcicament }}</td>
            </tr>
            <td>
                <div class="login-icon ml-2">
                    <a class="" href="{{ path('prescription_index') }}"> back to list </a>

                    <a class="" href="{{ path('prescription_edit', {'id': prescription.id}) }}"> edit </a>
                </div>
            </td>
        </tbody>
    </table>

    {{ include('prescription/_delete_form.html.twig') }}
{% endblock %}