src/Entity/Paiement.php
<?php

namespace App\Entity;

use App\Repository\PaiementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PaiementRepository::class)
 */
class Paiement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $mode_paiment;

    /**
     * @ORM\Column(type="float")
     */
    private $montant_paye;

    /**
     * @ORM\Column(type="float")
     */
    private $montantnon_paye;

    /**
     * @ORM\OneToMany(targetEntity=Facture::class, mappedBy="paiment")
     */
    private $facture;

    public function __construct()
    {
        $this->facture = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModePaiment(): ?string
    {
        return $this->mode_paiment;
    }

    public function setModePaiment(string $mode_paiment): self
    {
        $this->mode_paiment = $mode_paiment;

        return $this;
    }

    public function getMontantPaye(): ?float
    {
        return $this->montant_paye;
    }

    public function setMontantPaye(float $montant_paye): self
    {
        $this->montant_paye = $montant_paye;

        return $this;
    }

    public function getMontantnonPaye(): ?float
    {
        return $this->montantnon_paye;
    }

    public function setMontantnonPaye(float $montantnon_paye): self
    {
        $this->montantnon_paye = $montantnon_paye;

        return $this;
    }

    /**
     * @return Collection|Facture[]
     */
    public function getFacture(): Collection
    {
        return $this->facture;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->facture->contains($facture)) {
            $this->facture[] = $facture;
            $facture->setPaiment($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->facture->contains($facture)) {
            $this->facture->removeElement($facture);
            // set the owning side to null (unless already changed)
            if ($facture->getPaiment() === $this) {
                $facture->setPaiment(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getId();
    }
}

src/Form/PaiementType.php
<?php

namespace App\Form;

use App\Entity\Paiement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaiementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mode_paiment')
            ->add('montant_paye')
            ->add('montantnon_paye')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Paiement::class,
        ]);
    }
}

src/Controller/PaiementController.php
<?php

namespace App\Controller;

use App\Entity\Paiement;
use App\Form\PaiementType;
use App\Repository\PaiementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/paiement")
 */
class PaiementController extends AbstractController
{
    /**
     * @Route("/", name="paiement_index", methods={"GET"})
     */
    public function index(PaiementRepository $paiementRepository): Response
    {
        return $this->render('paiement/index.html.twig', [
            'paiements' => $paiementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="paiement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $paiement = new Paiement();
        $form = $this->createForm(PaiementType::class, $paiement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($paiement);
            $entityManager->flush();

            return $this->redirectToRoute('paiement_index');
        }

        return $this->render('paiement/new.html.twig', [
            'paiement' => $paiement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="paiement_show", methods={"GET"})
     */
    public function show(Paiement $paiement): Response
    {
        return $this->render('paiement/show.html.twig', [
            'paiement' => $paiement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="paiement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Paiement $paiement): Response
    {
        $form = $this->createForm(PaiementType::class, $paiement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('paiement_index');
        }

        return $this->render('paiement/edit.html.twig', [
            'paiement' => $paiement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="paiement_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Paiement $paiement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$paiement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($paiement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('paiement_index');
    }
}

templates/paiement/_delete_form.html.twig
<form method="post" action="{{ path('paiement_delete', {'id': paiement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ paiement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/paiement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/paiement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Paiement{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Edit Paiement</h1>

    {{ include('paiement/_form.html.twig', {'button_label': 'Update'}) }}

<div class="login-icon ml-2">
    <a class="" href="{{ path('paiement_index') }}"> back to list </a>
</div>
    {{ include('paiement/_delete_form.html.twig') }}
{% endblock %}

templates/paiement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement index{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Paiement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Mode_paiment</th>
                <th>Montant_paye</th>
                <th>Montantnon_paye</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for paiement in paiements %}
            <tr>
                <td>{{ paiement.id }}</td>
                <td>{{ paiement.modePaiment }}</td>
                <td>{{ paiement.montantPaye }}</td>
                <td>{{ paiement.montantnonPaye }}</td>
                <td><div class="login-icon ml-2">
                    <a class="" href="{{ path('paiement_show', {'id': paiement.id}) }}"> show </a>
                    <a class="" href="{{ path('paiement_edit', {'id': paiement.id}) }}"> edit </a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="login-icon ml-2">
<a class="" href="{{ path('paiement_new') }}"> Create new </a>
</div>

<div class="login-icon ml-2">
<a class="" href="{{ path('admin') }}"> Page admin </a>
</div>

{% endblock %}

templates/paiement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Paiement{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Create new Paiement</h1>

    {{ include('paiement/_form.html.twig') }}
<div class="login-icon ml-2">
    <a class="" href="{{ path('paiement_index') }}"> back to list </a>
</div>

{% endblock %}

templates/paiement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Paiement{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Paiement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ paiement.id }}</td>
            </tr>
            <tr>
                <th>Mode_paiment</th>
                <td>{{ paiement.modePaiment }}</td>
            </tr>
            <tr>
                <th>Montant_paye</th>
                <td>{{ paiement.montantPaye }}</td>
            </tr>
            <tr>
                <th>Montantnon_paye</th>
                <td>{{ paiement.montantnonPaye }}</td>
            </tr>
            <td>
                <div class="login-icon ml-2">
                    <a class="" href="{{ path('paiement_index') }}"> back to list </a>

                    <a class="" href="{{ path('paiement_edit', {'id': paiement.id}) }}"> edit </a>
                </div>
            </td>
        </tbody>
    </table>

    {{ include('paiement/_delete_form.html.twig') }}
{% endblock %}