src/Entity/FicheTraitement.php
<?php

namespace App\Entity;

use App\Repository\FicheTraitementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FicheTraitementRepository::class)
 */
class FicheTraitement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbr_fiche;

    /**
     * @ORM\OneToMany(targetEntity=Lignetraitement::class, mappedBy="fiche")
     */
    private $lignetraitement;

    /**
     * @ORM\OneToMany(targetEntity=Facture::class, mappedBy="fiche")
     */
    private $facture;

    /**
     * @ORM\ManyToOne(targetEntity=Patient::class, inversedBy="fichetraitement")
     * @ORM\JoinColumn(nullable=false)
     */
    private $patient;

    public function __construct()
    {
        $this->lignetraitement = new ArrayCollection();
        $this->facture = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNbrFiche(): ?int
    {
        return $this->nbr_fiche;
    }

    public function setNbrFiche(int $nbr_fiche): self
    {
        $this->nbr_fiche = $nbr_fiche;

        return $this;
    }

    /**
     * @return Collection|Lignetraitement[]
     */
    public function getLignetraitement(): Collection
    {
        return $this->lignetraitement;
    }

    public function addLignetraitement(Lignetraitement $lignetraitement): self
    {
        if (!$this->lignetraitement->contains($lignetraitement)) {
            $this->lignetraitement[] = $lignetraitement;
            $lignetraitement->setFiche($this);
        }

        return $this;
    }

    public function removeLignetraitement(Lignetraitement $lignetraitement): self
    {
        if ($this->lignetraitement->contains($lignetraitement)) {
            $this->lignetraitement->removeElement($lignetraitement);
            // set the owning side to null (unless already changed)
            if ($lignetraitement->getFiche() === $this) {
                $lignetraitement->setFiche(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Facture[]
     */
    public function getFacture(): Collection
    {
        return $this->facture;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->facture->contains($facture)) {
            $this->facture[] = $facture;
            $facture->setFiche($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->facture->contains($facture)) {
            $this->facture->removeElement($facture);
            // set the owning side to null (unless already changed)
            if ($facture->getFiche() === $this) {
                $facture->setFiche(null);
            }
        }

        return $this;
    }

    public function getPatient(): ?Patient
    {
        return $this->patient;
    }

    public function setPatient(?Patient $patient): self
    {
        $this->patient = $patient;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getPatient();
    }


}

src/Form/FicheTraitementType.php
<?php

namespace App\Form;

use App\Entity\FicheTraitement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FicheTraitementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nbr_fiche')
            ->add('patient')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => FicheTraitement::class,
        ]);
    }
}

src/Controller/FicheTraitementController.php
<?php

namespace App\Controller;

use App\Entity\FicheTraitement;
use App\Form\FicheTraitementType;
use App\Repository\FicheTraitementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/fiche/traitement")
 */
class FicheTraitementController extends AbstractController
{
    /**
     * @Route("/", name="fiche_traitement_index", methods={"GET"})
     */
    public function index(FicheTraitementRepository $ficheTraitementRepository): Response
    {
        return $this->render('fiche_traitement/index.html.twig', [
            'fiche_traitements' => $ficheTraitementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="fiche_traitement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ficheTraitement = new FicheTraitement();
        $form = $this->createForm(FicheTraitementType::class, $ficheTraitement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ficheTraitement);
            $entityManager->flush();

            return $this->redirectToRoute('fiche_traitement_index');
        }

        return $this->render('fiche_traitement/new.html.twig', [
            'fiche_traitement' => $ficheTraitement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fiche_traitement_show", methods={"GET"})
     */
    public function show(FicheTraitement $ficheTraitement): Response
    {
        return $this->render('fiche_traitement/show.html.twig', [
            'fiche_traitement' => $ficheTraitement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="fiche_traitement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, FicheTraitement $ficheTraitement): Response
    {
        $form = $this->createForm(FicheTraitementType::class, $ficheTraitement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('fiche_traitement_index');
        }

        return $this->render('fiche_traitement/edit.html.twig', [
            'fiche_traitement' => $ficheTraitement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fiche_traitement_delete", methods={"DELETE"})
     */
    public function delete(Request $request, FicheTraitement $ficheTraitement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ficheTraitement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ficheTraitement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('fiche_traitement_index');
    }
}

templates/fiche_traitement/_delete_form.html.twig
<form method="post" action="{{ path('fiche_traitement_delete', {'id': fiche_traitement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fiche_traitement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fiche_traitement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fiche_traitement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Fiche Traitement{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Edit Fiche Traitement</h1>


    {{ include('fiche_traitement/_form.html.twig', {'button_label': 'Update'}) }}

<div class="login-icon ml-2">
    <a class="" href="{{ path('fiche_traitement_index') }}"> back to list </a>
</div>
    {{ include('fiche_traitement/_delete_form.html.twig') }}
{% endblock %}

templates/fiche_traitement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FicheTraitement index{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>FicheTraitement index</h1>


    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nbr_fiche</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fiche_traitement in fiche_traitements %}
            <tr>
                <td>{{ fiche_traitement.id }}</td>
                <td>{{ fiche_traitement.nbrFiche }}</td>
                <td><div class="login-icon ml-2">
                    <a class="" href="{{ path('fiche_traitement_show', {'id': fiche_traitement.id}) }}"> show </a>
                    <a class="" href="{{ path('fiche_traitement_edit', {'id': fiche_traitement.id}) }}"> edit </a>
                    </div>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="login-icon ml-2">
<a class="" href="{{ path('fiche_traitement_new') }}"> Create new </a>
</div>

<div class="login-icon ml-2">
<a class="" href="{{ path('admin') }}"> Page admin </a>
</div>
{% endblock %}

templates/fiche_traitement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Fiche Traitement{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Create new Fiche Traitement</h1>


    {{ include('fiche_traitement/_form.html.twig') }}

<div class="login-icon ml-2">
    <a class="" href="{{ path('fiche_traitement_index') }}"> back to list </a>
</div>
{% endblock %}

templates/fiche_traitement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche Traitement{% endblock %}

{% block body %}
<h1><span class="fa fa-stethoscope" aria-hidden="true"></span>Fiche Traitement</h1>


    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fiche_traitement.id }}</td>
            </tr>
            <tr>
                <th>Nbr_fiche</th>
                <td>{{ fiche_traitement.nbrFiche }}</td>
            </tr>
            <tr>
                <th>patient</th>
                <td>{{ fiche_traitement.patient  }}</td>
            </tr>
            <td>
                <div class="login-icon ml-2">
                    <a class="" href="{{ path('fiche_traitement_index') }}"> back to list </a>

                    <a class="" href="{{ path('fiche_traitement_edit', {'id': fiche_traitement.id}) }}"> edit </a>
                </div>
            </td>
        </tbody>
    </table>

    {{ include('fiche_traitement/_delete_form.html.twig') }}
{% endblock %}